name: Hello World

env:
    NOM: "eneko"
    PRENOM: "CORREIA"
    EMAIL: "monsuperemail@gmail.com"

on:
    push:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World command
              run: echo "Hello World"
    nom:
        runs-on: ubuntu-latest
        steps:
            - name: Afficher nom
              run: |
                  echo "Nom : ${{ env.NOM }}"
    prenom:
        runs-on: ubuntu-latest
        steps:
            - name: Afficher prenom
              run: |
                  echo "Prenom : ${{ env.PRENOM }}"
    script: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: script_python
              run: python3 script.py